print("Welcome to the tip calculator!\n")
total = float(input("What was the total bill? $"))
tip = int(input("How much tip would you like to give? 10, 12, or 15? "))
people_count = int(input("How many people to split the bill? "))
split = round((total * (tip / 100 + 1)) / people_count, 2)
print(f"Each person should pay: ${split}")
